### ISSUE TITLE
Missing benchmark-points.txt file in ComputingTheConvexHullOnGpu project

### ISSUE THREAD

**Issue by legenself** [timiskhakov/ComputingTheConvexHullOnGpu#2]
In the ComputingTheConvexHullOnGpu project, there is a reference to a benchmark-points.txt file in the code:

```cs
var file = Path.Combine(Directory.GetCurrentDirectory(), "Assets", "benchmark-points.txt");
```

However, it seems that the benchmark-points.txt file is missing from the project.

**Comment by timiskhakov** [comment]
I think I didn't include it on purpose as the file was containing 10 million points. However, it can be created programmatically as it's just a text file containing pairs of random `float` values.

**Comment by legenself** [comment]
Ok, Thank you!
