### ISSUE TITLE
Decreased GPU Performance with 200-input Dataset on Benchmark Test

### ISSUE THREAD

**Issue by legenself** [timiskhakov/ComputingTheConvexHullOnGpu#3]
While running the benchmark test using the 200-input dataset in our project, I observed that the GPU's performance was notably worse. I dont know what happened
```

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.22000
Intel Core i5-8300H CPU 2.30GHz (Coffee Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.100
  [Host]     : .NET 6.0.26 (6.0.2623.60508), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET 6.0.26 (6.0.2623.60508), X64 RyuJIT


|          Method |          Mean |        Error |        StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------- |--------------:|-------------:|--------------:|--------:|------:|------:|----------:|
|        Baseline |      48.58 us |     0.953 us |      2.703 us |  0.8545 |     - |     - |      4 KB |
| CpuParallelized |     899.29 us |    30.536 us |     90.037 us | 14.6484 |     - |     - |     61 KB |
| GpuParallelized | 139,870.86 us | 3,962.716 us | 11,684.157 us |       - |     - |     - |  3,747 KB |
```

**Comment by timiskhakov** [comment]
The 200-input dataset is likely too small to get any benefits from parallelization. That is, the overhead that comes with parallelization — spanning threads, copying data, synchronizing — outweighs the baseline on a small scale. But as the data gets bigger, using many CPU/GPU cores becomes more beneficial. IIRC in [the blog post](https://timiskhakov.github.io/posts/computing-the-convex-hull-on-gpu) benchmarks are done on a dataset consisting of 10 million points. In hindsight, I should have included additional benchmarks with varying dataset sizes to demonstrate how solution speeds grow.
